/**
 * Catalog of the endpoints the server really serves, with the spec path of each one.
 * It feeds /api/v1/openapi.json and is checked by a test, so it cannot drift from the routes.
 */

export const API_CATALOG = [
  { method: 'GET', path: '/api/v1/app/config', screen: 'PAX-001', summary: 'Remote config and version handshake' },
  { method: 'POST', path: '/api/v1/auth/passenger/otp/request', screen: 'PAX-002', summary: 'Request an SMS OTP' },
  { method: 'POST', path: '/api/v1/auth/passenger/otp/verify', screen: 'PAX-003', summary: 'Exchange the OTP for a session token' },
  { method: 'GET', path: '/api/v1/passenger/home-feed', screen: 'PAX-004', summary: 'Home feed' },
  { method: 'GET', path: '/api/v1/routes/stops/search', screen: 'PAX-005', summary: 'Search stops and stations' },
  { method: 'GET', path: '/api/v1/trips/search', screen: 'PAX-006', summary: 'Search trips' },
  { method: 'GET', path: '/api/v1/trips/{tripId}', screen: 'PAX-007', summary: 'Trip detail' },
  { method: 'GET', path: '/api/v1/trips/{tripId}/stops', screen: 'PAX-008', summary: 'Selectable pickup and drop-off stops' },
  { method: 'GET', path: '/api/v1/trips/{tripId}/seat-map', screen: 'PAX-009', summary: 'Seat map with live holds' },
  { method: 'POST', path: '/api/v1/trips/{tripId}/seats/hold', screen: 'PAX-010', summary: 'Hold seats for 10 minutes' },
  { method: 'DELETE', path: '/api/v1/trips/{tripId}/seats/hold', screen: 'PAX-010', summary: 'Release the hold of the caller' },
  { method: 'POST', path: '/api/v1/bookings/create', screen: 'PAX-012', summary: 'Create a booking and its payment order' },
  { method: 'POST', path: '/api/v1/passenger/payments/{orderId}/verify-status', screen: 'PAX-013', summary: 'Resume polling or ask for reconciliation' },
  { method: 'GET', path: '/api/v1/payments/{orderId}/status', screen: 'PAX-014', summary: 'Authoritative payment status' },
  { method: 'GET', path: '/api/v1/bookings/{bookingId}', screen: 'PAX-015', summary: 'Booking and tickets by id or PNR' },
  { method: 'GET', path: '/api/v1/passenger/tickets', screen: 'PAX-016', summary: 'Ticket wallet' },
  { method: 'GET', path: '/api/v1/tickets/{ticketId}', screen: 'PAX-017', summary: 'Ticket with its rotating QR' },
  { method: 'GET', path: '/api/v1/passenger/orders/{orderId}/group-qr', screen: 'PAX-017', summary: 'Group boarding QR' },
  { method: 'POST', path: '/api/v1/passenger/tickets/{ticketId}/delegate', screen: 'PAX-017', summary: 'Share a ticket with a companion' },
  { method: 'GET', path: '/api/v1/trips/{tripId}/tracking', screen: 'PAX-018', summary: 'Live tracking snapshot' },
  { method: 'GET', path: '/api/v1/passenger/notifications', screen: 'PAX-020', summary: 'Notifications' },
  { method: 'POST', path: '/api/v1/passenger/tickets/{ticketId}/cancel', screen: 'PAX-021', summary: 'Cancel a ticket and request a refund' },
  { method: 'GET', path: '/api/v1/passenger/profile', screen: 'PAX-022', summary: 'Profile from the session token' },
  { method: 'GET', path: '/api/v1/trips/{tripId}/replacement-info', screen: 'PAX-024', summary: 'Vehicle replacement notice' },
  { method: 'GET', path: '/api/v1/trips/{tripId}/disruptions', screen: 'PAX-025', summary: 'Delay and disruption notice' },
  { method: 'POST', path: '/api/v1/auth/driver/login', screen: 'DRI-001', summary: 'Driver login' },
  { method: 'GET', path: '/api/v1/driver/trips/today', screen: 'DRI-002', summary: 'Trips assigned for today' },
  { method: 'GET', path: '/api/v1/driver/trips/{tripId}', screen: 'DRI-003', summary: 'Pre-start trip detail' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/readiness', screen: 'DRI-004', summary: 'Submit the readiness checklist' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/start', screen: 'DRI-005', summary: 'Start the trip' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/telemetry', screen: 'DRI-006', summary: 'Send a GPS ping' },
  { method: 'GET', path: '/api/v1/driver/trips/{tripId}/manifest', screen: 'DRI-007', summary: 'Passenger manifest' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/onboard-hail', screen: 'DRI-007', summary: 'Board a hail passenger' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/stops/{stopId}/arrive', screen: 'DRI-008', summary: 'Confirm arrival at a stop' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/boarding', screen: 'DRI-009', summary: 'Board by QR, group QR or offline ticket' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/boarding/manual', screen: 'DRI-010', summary: 'Board by PIN or by hand' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/tickets/{ticketId}/no-show', screen: 'DRI-011', summary: 'Mark a no-show' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/payments/cod-collect', screen: 'DRI-012', summary: 'Collect cash on delivery' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/incidents', screen: 'DRI-019', summary: 'Report an incident' },
  { method: 'POST', path: '/api/v1/driver/telemetry/batch-replay', screen: 'DRI-015', summary: 'Replay offline telemetry' },
  { method: 'POST', path: '/api/v1/driver/trips/{tripId}/end', screen: 'DRI-017', summary: 'End the trip and reconcile cash' },
  { method: 'GET', path: '/api/v1/driver/system/gps-health', screen: 'DRI-014', summary: 'GPS health' },
  { method: 'GET', path: '/api/v1/driver/system/diagnostics-ping', screen: 'DRI-016', summary: 'Diagnostics ping' },
  { method: 'GET', path: '/api/v1/driver/profile', screen: 'DRI-018', summary: 'Driver profile' },
  { method: 'POST', path: '/api/v1/auth/staff/login', screen: 'MGR-001', summary: 'Staff login' },
  { method: 'GET', path: '/api/v1/ops/dashboard/kpis', screen: 'MGR-002', summary: 'Dashboard figures' },
  { method: 'GET', path: '/api/v1/ops/fleet/live-positions', screen: 'MGR-003', summary: 'Live vehicle positions' },
  { method: 'GET', path: '/api/v1/ops/vehicles', screen: 'MGR-005', summary: 'Vehicle list' },
  { method: 'GET', path: '/api/v1/ops/routes', screen: 'MGR-008', summary: 'Route list' },
  { method: 'GET', path: '/api/v1/ops/trips', screen: 'MGR-010', summary: 'Trip list' },
  { method: 'GET', path: '/api/v1/ops/trips/{tripId}/master', screen: 'MGR-012', summary: 'Trip detail' },
  { method: 'GET', path: '/api/v1/ops/trips/{tripId}/seat-matrix', screen: 'MGR-013', summary: 'Trip seat inventory' },
  { method: 'GET', path: '/api/v1/ops/dispatch/matrix', screen: 'MGR-014', summary: 'Dispatch board' },
  { method: 'GET', path: '/api/v1/ops/drivers', screen: 'MGR-015', summary: 'Driver list' },
  { method: 'GET', path: '/api/v1/ops/bookings', screen: 'MGR-017', summary: 'Booking search' },
  { method: 'GET', path: '/api/v1/ops/bookings/{bookingId}', screen: 'MGR-018', summary: 'Booking detail by PNR' },
  { method: 'POST', path: '/api/v1/ops/pos/orders', screen: 'MGR-020', summary: 'Counter ticket sale' },
  { method: 'POST', path: '/api/v1/ops/pos/hotline-hold', screen: 'MGR-020', summary: 'Hotline seat hold' },
  { method: 'POST', path: '/api/v1/ops/refunds/{refundId}/process', screen: 'MGR-022', summary: 'Approve or reject a refund' },
  { method: 'POST', path: '/api/v1/ops/trips/{tripId}/replace-vehicle', screen: 'MGR-023', summary: 'Emergency vehicle replacement' },
  { method: 'POST', path: '/api/v1/ops/trips/{tripId}/delay', screen: 'MGR-024', summary: 'Declare a trip delay' },
  { method: 'GET', path: '/api/v1/ops/alerts', screen: 'MGR-025', summary: 'Operations alerts' },
  { method: 'GET', path: '/api/v1/ops/reports/yield', screen: 'MGR-027', summary: 'Executive report' },
  { method: 'GET', path: '/api/v1/ops/audit-logs', screen: 'MGR-028', summary: 'Audit log' },
  { method: 'POST', path: '/api/v1/webhooks/vietqr/ipn', screen: 'PAX-014', summary: 'Bank transfer notification' },
  { method: 'GET', path: '/health', screen: '', summary: 'Liveness and service status' },
  { method: 'GET', path: '/api/v1/openapi.json', screen: '', summary: 'Machine-readable API description' }
];
